### ISSUE TITLE
1.4.9 to 1.5.8 update issue

### ISSUE THREAD

**Issue by yavuz** [taxjar/taxjar-magento2-extension#163] opened 2020-10-28 10:04 UTC
Hi,

### Description
I want to update from 1.4.9 to 1.5.8. But I get error when I run setup:upgrade.

`bin/magento setup:upgrade`

```
Module 'Taxjar_SalesTax':
Upgrading data.. 
[[SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '14-General' for key 'EAV_ATTRIBUTE_GROUP_ATTRIBUTE_SET_ID_ATTRIBUTE_GROUP_NAME', query was: INSERT INTO `eav_attribute_group` (`attribute_set_id`, `attribute_group_name`, `default_id`, `sort_order`, `attribute_group_code`) VALUES (?, ?, ?, ?, ?)
```

### Versions

- [x] Magento 2.3

- [x] Magento Cloud

- [x] PHP 7.x

Database Result:
![database](https://user-images.githubusercontent.com/98246/97421828-02b40e80-191e-11eb-9e63-3051c9a55d68.jpg)

**Comment by ryanreeves-taxjar** [comment] 2020-10-28 16:18
Thanks for reporting this issue @yavuz!  We've opened a ticket internally to investigate and will update you with our progress!

**Comment by sethobey** [comment] 2021-11-18 23:50
Hi @yavuz,
I am unable to reproduce this issue and will be closing it as we are currently at v1.7.1, but please feel free to re-open this ticket if you are still experiencing this problem!

**Closed by sethobey** 2021-11-18 23:50 UTC
Labels: bug

**Comment by ducto** [comment] 2021-12-10 20:03
Hello,

I am having the exact same issue also with Magento 2.3, the version is 1.7, can you check?

Upgrading data... SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4-general' for key 'EAV_ATTRIBUTE_GROUP_ATTRIBUTE_SET_ID_ATTRIBUTE_GROUP_CODE', query was: INSERT INTO `eav_attribute_group` (`attribute_set_id`, `attribute_group_name`, `default_id`, `sort_order`, `attribute_group_code`) VALUES (?, ?, ?, ?, ?)

Thank you,
Duc

**Comment by sethobey** [comment] 2021-12-10 21:20
Hi @ducto,

I can't be sure if this is an issue with our extension based on the information provided, but a quick Google of that error would recommend taking a DB backup before removing the offending primary key entry and re-attempting the `setup:upgrade` command.

https://magento.stackexchange.com/questions/301570/integrity-constraint-violation-1062-duplicate-entry-magento-2-3-0

Best of luck!

**Comment by ducto** [comment] 2021-12-12 18:32
Hello @sethobey 

Thank you for your feedback. The error post you shared is actually not related as in my case which is EAV_ATTRIBUTE_GROUP_ATTRIBUTE_SET_ID_ATTRIBUTE_GROUP_CODE unique key of 2 field's values  '4-general' 

I also tried to removed the rows with issue and found that taxjar extension creates new records with similar value pair (other fields values were different ) and after that, I cannot access to Product Detail page anymore.

I am pretty sure that the issue is related to taxjar module because if I disabled the module and run setup:upgrade, I do not have any error.

Yours sincerely

**Comment by sethobey** [comment] 2021-12-12 22:53
Hey @ducto,

Sorry to hear you're still having trouble with this!

I gave it another try and once again was unable to reproduce the described error. I've attached the console output log if you'd like to look, but I began by installing v1.4.9 via Composer, enabled the module, compiled, and ran setup. After verifying installation, use Composer to require updated version(s) of module, and ran the `setup:upgrade` command without issue.

If it is an issue with this module, and you are able to provide clear steps to reproduce this bug, I'm glad to take another look!

[163_attempt_5.log](https://github.com/taxjar/taxjar-magento2-extension/files/7700029/163_attempt_5.log)

**Comment by ducto** [comment] 2021-12-15 18:21
Hello @sethobey 

Thank you for the hint. It seems that downgrade the extension to version v1.4.9 works as expected. We are further checking it and will keep you informed.

Yours sincerely

**Comment by ducto** [comment] 2021-12-17 04:33
Hello @sethobey 

Even thought the version 1.4.9 works for us, unfortunately we cannot use it as that version does not have Sandbox option. Per feedback by email from support@taxjar.com team:

"
Thanks for reaching out to us here!

I reviewed your account and it looks like this option may be missing due to the version of our Magento Extension you're currently using.
This change was launched in our Magento extension version 1.5.4 in June, 2020 -- you can see the release notes regarding this here.

If I had to assume, you are running a version of our Magento2 extension that pre-dates 1.5.4. You can verify this by enabling Debug Mode in Magento and observing what version you see next to "TaxJar Version".
If this is the case, you should be able to see the sandbox option after upgrading to the latest version (currently up to 1.6.3, includes many fixes and features since 1.5.4 even!)

Let us know if you find you are already on a later version or still are not able to set up the sandbox environment after upgrading the TaxJar extension. We'd be happy to help however we can!
"

Unfortunately, if we upgrade the version to the latest, the issue comes back again. We are forced to run the setup:upgrade command after upgrading version else we will have the below error:

"
Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory.
The following modules are outdated:
Taxjar_SalesTax data: current version - 1.0.3, required version - 1.0.6
"

Upgrading data.. SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4-general' for key 'EAV_ATTRIBUTE_GROUP_ATTRIBUTE_SET_ID_ATTRIBUTE_GROUP_CODE', query was: INSERT INTO `eav_attribute_group` (`attribute_set_id`, `attribute_group_name`, `default_id`, `sort_order`, `attribute_group_code`) VALUES (?, ?, ?, ?, ?)


Can you check and advise?

Yours sincerely

**Comment by ducto** [comment] 2021-12-20 02:57
Hello @sethobey 

I found that I am having issue even with version 1.4.9, in Admin portal, when I tried to go to Catalog -> Product and edit a product, I have error:

1 exception(s):
Exception #0 (ReflectionException): Class Taxjar\SalesTax\Model\Attribute\Source\Category does not exist

I did do php bin/magento setup:upgrade and php bin/magento setup:di:compile as usual. So I had to disable the module

**Comment by sethobey** [comment] 2021-12-20 16:46
Hello @ducto

I apologize if my last reply wasn't clear enough, but I _do not suggest that you use v1.4.9_, I was only attempting to replicate the issue! Since the original issue was in upgrading from v1.4.9 -> v1.5.8, and you mentioned in your original comment that you were experiencing an issue with v1.7.x, I attempted installing v1.4.9, then upgrading from v1.4.9 -> v1.5.8 -> v1.7.0, but did not encounter any errors, as shown in the output log that I attached in my previous reply.

The origin of the first issue you are experiencing with EAV attribute is incredibly difficult to diagnose without access to your environment, but the only way I see the potential of the TaxJar module creating a duplicate entry like you are seeing is if somehow the section of script in `Taxjar\SalesTax\Setup\UpgradeData.php` for that schema version has been executed, but the schema version for the TaxJar module that is recorded in the DB is not consistent (schema version stored on table `setup_module`).

The error that your are now experiencing with v.1.4.9, while not entirely clear WHY, does make sense because class Taxjar\SalesTax\Model\Attribute\Source\Category should not exist in v1.4.9.

You can attempt the troubleshooting steps I've outlined below if you feel comfortable with it, but remember to take a backup of your database before proceeding!

1. Ensure you are requiring `"taxjar/module-taxjar": "^1.7.*"` in your `composer.json`. If you see any other version present, it will be necessary to run `composer require taxjar/module-taxjar:^1.7.*`
2. Next, inspect the `setup_module` table in your database for your TaxJar module's "schema version". Ensure the corresponding value for the TaxJar extension is "1.0.6". Manually update this value if necessary (I believe this is safe, because the EAV attribute error that you are experiencing would indicate that the `UpgradeData.php` script has already been executed).
3. Attempt command `bin/magento setup:upgrade && bin/magento setup:di:compile`. (manually setting the schema version should bypass execution of the UpgradeData script and avoid the error you are experiencing when running `bin/magento setup:upgrade`)

If you give this a try, please follow up to let me know if this resolves your issue!

**Comment by ducto** [comment] 2021-12-21 11:14
Hello @sethobey ,

Thank you for your feedback, yes, manually update extension's schema version to "1.0.6" directly in DB did the trick. Our Dev environment is at version 1.7 now and my manager is checking it, we will keep you informed if there is any further issue.

I am just curious that forced jumping schema version like that will ignore all the database changes from 1.0.3 (the version I had) to 1.0.6, will there be any issue and cause any TaxJar's features does not work properly?

Yours sincerely

**Comment by sethobey** [comment] 2021-12-21 16:07
Hello again @ducto,

Glad to hear that appears to have helped!

Without inspecting your database, I can't be _entirely_ certain, but I believe manually updating the version schema/data version entries in for the module should not cause any issues, because I believe the UpgradeData script has already been ran.

Take a look at the file `\Taxjar\SalesTax\Setup\UpgradeData.php`. You'll see it compares our module's schema version and if the condition evaluates "true", the block will execute, doing something like adding an EAV attribute. You should be able to work your way through the UpgradeData file, inspecting which EAV attributes WOULD be created for a specific schema version, and then manually inspecting which values exist in your database to ultimately determine if any schema version specified in `UpgradeData.php` was not successfully installed/updated.

Just quick example, if you don't want to manually inspect the table, since the most recent EAV entry added was for TaxJar Product Tax Code, you should be able to execute the following SQL query to determine if that attribute exists:

`SELECT COUNT(1) FROM eav_attribute WHERE attribute_code = 'tj_ptc';`

A boolean (0 or 1) should be returned whether the value exists. If the above SQL query returns "0", then your schema is _NOT_ accurate and some troubleshooting is in order.

Let me know if there is anything else I can do to help!
