### ISSUE TITLE
Popup For Admin Not in Code

### ISSUE THREAD

**Issue by fredpope** [taxjar/taxjar-magento2-extension#38] opened 2018-11-03 14:40 UTC
When I deploy the code into a 2.2.6 instance and I try connect to taxjar from the admin, I am getting a 404 file not found error on this item 

/adminhtml/Magento/backend/en_us/taxjarPopup.js

I fixed this by adding a symbolic link for now to the correct location at Taxjar_SalesTax/js/popup.js

**Comment by dankoz51** [comment] 2018-11-09 18:52
having the same issue

**Comment by fastdivision** [comment] 2018-11-09 23:32
Thanks for reporting @fredpope and @dankoz51, we're looking into this issue!

**Comment by ryanreeves-taxjar** [comment] 2018-11-14 18:13
Thanks for your patience while we looked into this.  It appears that the error is from a cached "requirejs-config.js" file found in the pub/static folder.  You should be able to correct the problem by running this command from the console:

 php bin/magento setup:static-content:deploy

*note that you may need to add the '-f' flag to force it depending on your developer mode.  

Please let us know if this fixes the issue you're encountering!

**Comment by dankoz51** [comment] 2018-11-15 22:01
This has always been done as part of every deployment.  And does not seem to fix either problem.  I will try again.

**Comment by ryanreeves-taxjar** [comment] 2018-11-29 18:20
Hi @dankoz51 and @fredpope,

I wanted to check-in and see if you're still experiencing this issue.  Thanks!

**Comment by dankoz51** [comment] 2018-11-29 20:12
I created a symlink to fix this but then the registration screen is blank screen as reported on issue #39

**Comment by ryanreeves-taxjar** [comment] 2018-12-03 22:20
I'm going to go ahead and close this issue since we can't reproduce it in a vanilla installation of Magento.  If you're continuing to experience errors, please email our support team at [support@taxjar.com](mailto:support@taxjar.com)?  You can mention this issue and we will continue with more in-depth troubleshooting.

**Closed by ryanreeves-taxjar** 2018-12-03 22:20 UTC
